# Generated by Django 2.2 on 2022-01-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_products_available'),
        ('cart', '0002_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='prodt',
        ),
        migrations.AddField(
            model_name='items',
            name='prod',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.products'),
            preserve_default=False,
        ),
    ]
